# Generated by Django 5.1.15 on 2026-10-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HmmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimplifiedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(default='general', max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('urgency', models.CharField(default='Notice', max_length=50)),
                ('grounded_reference', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.hmmuser')),
            ],
            options={
                'db_table': 'django_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
